# Generated by Django 4.1.2 on 2022-10-11 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artiste',
            name='lyric',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='album.lyric'),
        ),
        migrations.AddField(
            model_name='artiste',
            name='song',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='album.song'),
        ),
        migrations.RemoveField(
            model_name='song',
            name='likes',
        ),
        migrations.AddField(
            model_name='song',
            name='likes',
            field=models.IntegerField(default='1112'),
            preserve_default=False,
        ),
    ]
