# Generated by Django 4.1.2 on 2022-10-24 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0003_alter_song_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artiste',
            name='lyric',
        ),
        migrations.AddField(
            model_name='song',
            name='lyric',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='album', to='album.lyric'),
        ),
        migrations.AlterField(
            model_name='song',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
