# Generated by Django 4.1.2 on 2022-10-24 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0004_remove_artiste_lyric_song_lyric_alter_song_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artiste',
            name='age',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='artiste',
            name='song',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='album.song'),
        ),
        migrations.AlterField(
            model_name='lyric',
            name='song_id',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='song',
            name='artiste_id',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='song',
            name='title',
            field=models.CharField(max_length=30),
        ),
    ]
